services:
  postgresql:
    image: postgres:11-alpine
    restart: no
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ../../../.data-heri-tny-demo/postgres:/var/lib/postgresql/data/pgdata
      - ./init-postgres:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
  valkey:
    image: valkey/valkey:8.0.3-alpine3.21
    restart: no
    environment:
      - VALKEY_USERNAME=${VALKEY_USERNAME}
      - VALKEY_PASSWORD=${VALKEY_PASSWORD}
      - VALKEY_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - 6379:6379
    volumes:
      - 'valkey_data:/bitnami/valkey/data'
volumes:
  valkey_data:
    driver: local
