services:
  postgresql:
    image: postgres:11-alpine
    restart: 'unless-stopped'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ../../.data-heri-tny-demo/postgres:/var/lib/postgresql/data/pgdata
      - ./init-postgres:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
  valkey:
    image: valkey/valkey:8.0.3-alpine3.21
    restart: 'unless-stopped'
    environment:
      - VALKEY_USERNAME=${VALKEY_USERNAME}
      - VALKEY_PASSWORD=${VALKEY_PASSWORD}
      - VALKEY_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - 6379:6379
    volumes:
      - 'valkey_data:/bitnami/valkey/data'
  demo-member-api:
    image: demo-member-api:latest
    # build: --format docker -t demo-member-api:latest .
    restart: 'unless-stopped'
    environment:
      POSTGRES_URL: ${POSTGRES_URL}
      VALKEY_HOST: valkey
      VALKEY_PORT: 6379
    ports:
      - 3000:3000
volumes:
  valkey_data:
    driver: local
