#!/bin/bash -e

cd docker
docker compose \
    --project-name heri_tny_demo \
    up --detach --remove-orphans

sleep 2

cd ..
nvm use $(cat .nvmrc)
npm run migrate up
npm run start -- --init-user

TEMP_DIRECTORY="temp"
if [ ! -d "$TEMP_DIRECTORY" ]; then
  mkdir -p "$TEMP_DIRECTORY"
  chmod 777 "$TEMP_DIRECTORY"
  echo "Temporary directory '$TEMP_DIRECTORY' created."
else
  echo "Temporary directory '$TEMP_DIRECTORY' already exists."
fi
