#!/bin/bash -e

TEMP_DIRECTORY="temp"
if [ ! -d "$TEMP_DIRECTORY" ]; then
  mkdir -p "$TEMP_DIRECTORY"
  chmod 777 "$TEMP_DIRECTORY"
  echo "Temporary directory '$TEMP_DIRECTORY' created."
else
  echo "Temporary directory '$TEMP_DIRECTORY' already exists."
fi

nvm use $(cat .nvmrc)
npm install
npm run build
podman rmi -f demo-member-api:latest
podman build --format docker -t demo-member-api:latest .

cd docker-deploy
podman-compose \
    --project-name heri-tny-demo \
    up --detach --remove-orphans

sleep 2

podman-compose \
    --project-name heri-tny-demo \
    up --detach --remove-orphans

sleep 2

cd ..
npm run migrate up
npm run start -- --init-user
