#!/bin/bash

OUTPUT_DIR="demo-member-api"
INPUT_ZIP="demo-member-api.zip"

rm -rf ~/$OUTPUT_DIR
mkdir ~/$OUTPUT_DIR
unzip /tmp/$INPUT_ZIP -d ~/$OUTPUT_DIR
cd ~/$OUTPUT_DIR
source deploy
cd ..
rm -f /tmp/extract "/tmp/$INPUT_ZIP"
