#!/bin/sh -e

POSTGRES_HOST=${POSTGRES_HOST:-localhost}
psql -v ON_ERROR_STOP=1 -h "$POSTGRES_HOST" --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    SELECT 'CREATE DATABASE "$POSTGRES_DB"' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname='$POSTGRES_DB')\gexec
EOSQL
